# About Application
name: amazon_clone_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

# Application Dependencies
dependencies:
#  Flutter Dependencies
  flutter:
    sdk: flutter

# For Requests to the Server
  http: ^0.13.4
#  iphone Icons
  cupertino_icons: ^1.0.2
#  State management
  provider: ^6.0.3
#  For local Storage
  shared_preferences: ^2.0.15
#  For badge in the CART icon
  badges: ^2.0.3
# For Sliding Carousel Image 
  carousel_slider: ^4.1.1
# For dotted borders
  dotted_border: ^2.0.0+2
# To pick file from local storage
  file_picker: ^3.0.4
  cloudinary_public: ^0.11.1
  animated_splash_screen: ^1.3.0

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

# Assets
  assets:
     - assets/images/